[phases.setup]
nixPkgs = ["nodejs-18_x", "python310", "pip"]

[phases.install]
cmds = [
  "npm ci --omit=dev --ignore-scripts || npm install",
  "pip install --no-cache-dir -r requirements.txt"
]

[phases.build]
cmds = [
  "npm run build"
]

[start]
cmd = "npm run start:production"
